lowdefy/lowdefy

packages/blockTools/jest.config.js, packages/blockTools/src/index.js, packages/blockTools/src/runMockRenderTests.js, packages/blocksAntd/demo/examples/Progress.yaml, packages/blocksAntd/src/blocks/Progress/Progress.json, packages/blocksAntd/tests/Progress.mock.test.js, packages/blocksAntd/tests/Progress.test.js, packages/blocksAntd/tests/__snapshots__/Progress.mock.test.js.snap, packages/blocksAntd/tests/__snapshots__/Progress.test.js.snap
(no diff status normal OR active)
=>  feat(blocksAntd): progress examples (no diff status normal OR active)

packages/build/src/build.js, packages/build/src/build/testSchema.test.js, packages/build/src/build/writeConfig.js, packages/build/src/build/writeConfig.test.js, packages/build/src/utils/appSchema.json
- Write config object to output.
- Add app name to schema.
=> fix(build): write config object to output in build

packages/renderer/src/Renderer.js, packages/renderer/src/utils/graphql/useGqlClient.js, packages/renderer/webpack.dev.js, packages/renderer/webpack.prod.js
@lowdefy/render
- Make graphql uri configurable, closes #250.
=> feat(renderer): make gql uri configurable, closes #250

packages/cli/package.json, packages/servers/serverDev/package.json, packages/servers/serverDocker/package.json, packages/servers/serverNetlify/package.json
- @lowdefy/block-tools should be a dev dependency.
=> fix(server): @lowdefy/block-tools should be a dev dependency

packages/graphql/jest-mongodb-config.js, packages/graphql/src/connections/MongoDBCollection/MongoDBAggregation/MongoDBAggregation.js, packages/graphql/src/connections/MongoDBCollection/MongoDBAggregation/MongoDBAggregation.test.js, packages/graphql/src/connections/MongoDBCollection/MongoDBInsertMany/MongoDBInsertMany.test.js, packages/graphql/src/connections/MongoDBCollection/MongoDBInsertOne/MongoDBInsertOne.test.js, packages/graphql/src/controllers/requestController.js, packages/graphql/src/controllers/requestController.test.js
=> fix(graphql): Mongodb, do not allow $out/$merge when write is false.

packages/blocks/blocksAntd/src/blocks/Descriptions/Descriptions.json, packages/docs/blocks/display/Descriptions.yaml, packages/docs/concepts/lowdefy-schema.yaml, packages/docs/introduction.yaml, packages/docs/operators/_ref.yaml
=> fix(blocks-antd): Fix Descriptions bordered property default value

packages/build/src/build/buildPages.js, packages/build/src/build/buildPages.test.js
=> fix(build): Nested context caused request to be created in wrong context.

packages/blocks/blocksAntd/src/blocks/Pagination/Pagination.js
onSizeChange event was triggered for onChange event.
=> fix(blocks-antd): Fix Pagination block onChange.

packages/engine/src/getContext.js, packages/engine/test/Actions/Validate.test.js, packages/engine/test/getContext.test.js
=> fix(engine): Fix required validation broken by dynamic operators.

packages/blocks/blocksAntd/src/blocks/PageHCF/PageHCF.json, packages/blocks/blocksAntd/src/blocks/PageHCSF/PageHCSF.json, packages/blocks/blocksAntd/src/blocks/PageHSCF/PageHSCF.json, packages/blocks/blocksAntd/src/blocks/PageHeaderMenu/PageHeaderMenu.json, packages/blocks/blocksAntd/src/blocks/PageSHCF/PageSHCF.json, packages/blocks/blocksAntd/src/blocks/PageSiderMenu/PageSiderMenu.json, packages/blocks/blocksAntd/src/blocks/Tabs/Tabs.json, packages/blocks/blocksBasic/src/blocks/Context/Context.json, packages/docs/concepts/events-and-actions.yaml, packages/docs/menus.yaml
=> fix: Fix Tabs blocks events in schema.

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/test-pulls.yml
=> Fix GitHub actions

packages/server/src/index.js
Closes: --
Increase body-parser payload limit to 5mb.
- [x ] Pull request is made to the "develop" branch
=> fix: Increase bodyParserConfig limit to 5mb.

packages/cli/src/commands/dev/dev.js
Closes #711
Fixes the error where the CLI dev server exits if the initial Lowdefy build fails.
=> Fix cli initial build error

packages/blocks/blocksAntd/src/blocks/ConfirmModal/ConfirmModal.js, packages/blocks/blocksAntd/src/blocks/Drawer/Drawer.js, packages/blocks/blocksAntd/src/blocks/Modal/Modal.js, packages/engine/src/Events.js, packages/engine/src/actions/CallMethod.js, packages/engine/test/Actions/CallMethod.test.js, packages/engine/test/Events.test.js
Closes: #740
Added modal close action chain event detection to ConfirmModal, Drawer and Modal.
=> feat(blocksAntd): Added modal close action chain event detection.

packages/docs/actions/JsAction.yaml, packages/engine/src/actions/JsAction.js, packages/engine/test/Actions/JsAction.test.js
Closes #747
This PR adds an object to the context received by `JsAction` that contains the Lowdefy actions.
=> Add Lowdefy actions to JsAction

packages/docs/concepts/events-and-actions.yaml, packages/engine/src/Actions.js, packages/engine/test/Actions/Actions.test.js
Closes #745 
The pull request adds an `async` option to actions which will allow them to be executed asynchronously in an event's action chain. 
Note: if this action throws an error, the event chain still completes successfully.
=> Actions async option

packages/blocks/blocksBasic/demo/examples/List.yaml, packages/blocks/blocksBasic/src/blocks/List/List.js, packages/blocks/blocksBasic/src/blocks/List/List.json, packages/blocks/blocksBasic/tests/__snapshots__/List.test.js.snap
Closes #744
Added List direction, wrapping and scrolling.
=> feat(blocksBasic): Added List direction, wrapping and scrolling.

packages/docs/actions/ResetValidation.yaml, packages/docs/actions/Validate.yaml, packages/docs/menus.yaml, packages/docs/pages.yaml, packages/engine/src/Blocks.js, packages/engine/src/actions/ResetValidation.js, packages/engine/src/actions/Validate.js, packages/engine/src/actions/index.js, packages/engine/src/getBlockMatcher.js, packages/engine/test/Actions/JsAction.test.js, packages/engine/test/Actions/ResetValidation.test.js, packages/engine/test/Block/validate.test.js, packages/engine/test/getBlockMatcher.test.js
Closes: #738 
New action `ResetValidation` to lower validation flags on input blocks after `Validate` has been called.
=> Add ResetValidation action

packages/build/src/utils/cachePromises.js, packages/build/src/utils/meta/getMeta.js, packages/cli/src/commands/dev/shell/index.html, packages/docs/templates/blocks/exampleTransformer.js
=> v3.20 fixes

packages/build/src/lowdefySchema.json
Closes #776 
Add debounce field to events in Lowdefy build schema.
=> fix(build): Add debounce to the build schema.

packages/docs/operators/_hash.yaml, packages/operators/src/node/hash.js, packages/operators/src/node/index.js, packages/operators/test/node/hash.test.js, packages/renderer/webpack.common.js
Closes #784
Added the `_hash` operator that allows generating various hashes on the server side (currently MD5, SHA1, SHA256, SHA512, but easily expandable).
=> feat(operators): Add _hash operator.

packages/server/src/index.js
Closes #789
Fixes `replaceAll not a function errror`.
=> Fix replaceAll not a function

packages/docs/concepts/blocks.yaml, packages/docs/concepts/events-and-actions.yaml, packages/docs/connections/AxiosHttp.yaml, packages/renderer/src/page/DisplayMessage.js, packages/renderer/src/page/Page.js, packages/renderer/src/page/block/Block.js, packages/renderer/src/page/block/CategorySwitch.js, packages/renderer/src/page/block/Context.js, packages/renderer/src/page/block/LoadBlock.js, packages/renderer/src/page/block/MountEvents.js, packages/renderer/src/page/block/OnEvents.js
Closes #778 
All blocks now has the `onMount` and `onMountAsync` events.
https://www.loom.com/share/25e8bbe4795641a4a46311daa57de6eb
=> onMount and onMountAsync events on all blocks.

packages/graphql/package.json, yarn.lock
This PR updates the MongoDB driver from v4.1.0 to v4.1.1 which contains some bug fixes.
=> fix(deps): Update dependency mongodb to v4.1.1.

packages/blocks/blocksAntd/demo/examples/Card.yaml, packages/blocks/blocksAntd/src/blocks/Card/Card.js, packages/blocks/blocksAntd/src/blocks/Card/Card.json, packages/blocks/blocksAntd/tests/__snapshots__/Card.mock.test.js.snap, packages/blocks/blocksAntd/tests/__snapshots__/Card.test.js.snap
Closes #810
The Card block now has an onClick event.
=> feat(blocksAntd): Added Card onClick event.

packages/docs/operators/_get.yaml
~~Closes #ISSUE_NUMBER~~
This PR adds an example to the `_get` operator docs as discussed in #822.
=> feat(docs): Add _get operator switch example.

.github/workflows/test-branches.yml
Closes #845 
Adds v4 branch to the list of branches to be tested in Github actions.
=> V4 branch config

packages/docs/operators/_array.yaml
=> feat: Add `_array.reduce` examples.

.github/ISSUE_TEMPLATE/bug_report.md
Fixes the bug report template label after "Bug" label changed.
=> chore: Update bug report template.

packages/docs/menus.yaml
=> fix: Add _switch operator to docs.

packages/docs/operators/_ref.yaml
This pull request fixes a `_ref` resolver function example in the docs. The existing example did not work.
=> fix(docs): Fix _ref resolver function example.

packages/build/src/build/testSchema.js, packages/build/src/build/testSchema.test.js, packages/build/src/utils/formatErrorMessage.js, packages/build/src/utils/formatErrorMessage.test.js
Closes #636
This PR adds an update to the formatErrorMessage function in build to show descriptive schema error paths.
=> fix(build): Updated formatErrorMessage function to show descriptive error paths.

packages/build/src/build/testSchema.js, packages/build/src/build/testSchema.test.js, packages/build/src/utils/formatErrorMessage.js, packages/build/src/utils/formatErrorMessage.test.js
Closes #121 
Better error messages at build time.
=> feat(build): Better error messages on build.

packages/server/src/components/Context.js, packages/server/src/components/Page.js, packages/server/src/components/Root.js, packages/server/src/components/block/Block.js, packages/server/src/components/block/MountEvents.js
=> Add mount events and simplify loading states

packages/build/src/build/buildConnections.js, packages/build/src/build/buildConnections.test.js, packages/build/src/build/buildPages/buildBlock/buildBlock.js, packages/build/src/build/buildPages/buildBlock/buildEvents.js, packages/build/src/build/buildPages/buildBlock/buildEvents.test.js, packages/build/src/build/buildPages/buildBlock/buildRequests.js, packages/build/src/build/buildPages/buildBlock/countBlockOperators.js, packages/build/src/build/buildPages/buildBlock/countBlockOperators.test.js, packages/build/src/build/buildPages/buildBlock/validateBlock.js, packages/build/src/build/buildPages/buildPage.js, packages/build/src/build/buildPages/buildRequests.test.js, packages/build/src/build/buildRefs/buildRefs.test.js, packages/build/src/build/writeTypes.js, packages/build/src/index.js, packages/build/src/lowdefySchema.js, packages/build/src/test/buildRefs/testBuildRefsResolver.js, packages/build/src/test/testContext.js, packages/build/src/utils/countOperators.js, packages/build/src/utils/countOperators.test.js, packages/build/src/utils/createCounter.js
=> feat(build): Count types during build.

.pnp.cjs, packages/build/package.json, packages/build/src/scripts/generateDefaultTypes.js, packages/build/src/scripts/run.js, packages/plugins/blocks/blocks-basic/package.json, packages/plugins/blocks/blocks-basic/src/types.js, packages/plugins/connections/connection-axios-http/package.json, packages/plugins/connections/connection-axios-http/src/types.js, yarn.lock
=> Add generateDefaultTypes script.

packages/build/src/build/buildIcons.js, packages/build/src/build/writePluginImports/writeConnectionImports.js, packages/build/src/build/writePluginImports/writeIconImports.js, packages/build/src/index.js
=> Build icons

.pnp.cjs, packages/build/src/build/updateServerPackageJson.js, packages/build/src/build/validateApp.js, packages/build/src/lowdefySchema.js, packages/server/next.config.js, yarn.lock
=> feat: Allow Less variables to be specified in server.

packages/blocks/blocksAntd/src/blocks/MultipleSelector/MultipleSelector.js, packages/blocks/blocksAntd/src/blocks/Selector/Selector.js
Closes #968
The user will now see the loading state between multiple searches that are debounced.
=> fix(blocksAntd): Added debouncing condition to Selector and MultipleSelector.

packages/plugins/blocks/blocks-markdown/src/blocks/MarkdownWithCode/MarkdownWithCode.js
Switch hljs from esm to cjs to fix build.
=> chore(blocks-markdown): Switch hljs from esm to cjs to fix build.

packages/build/src/build/validateApp.js, packages/build/src/build/validateApp.test.js, packages/build/src/build/validateConfig.js, packages/build/src/build/validateConfig.test.js, packages/build/src/lowdefySchema.js, packages/server-dev/next.config.js, packages/server/next.config.js
=> feat(build): Move app.style.lessVariables to config.theme.lessVariables.

packages/cli/src/commands/dev/runDevServer.js, packages/cli/src/commands/init/lowdefyFile.js, packages/cli/src/commands/start/runStart.js, packages/cli/src/index.js, packages/server-dev/src/manager/getContext.mjs, packages/server-dev/src/manager/processes/startServerProcess.mjs, packages/server-dev/src/manager/run.mjs
Add CLI, dev and prod server port settings.
=> feat: Add CLI, dev and prod server port settings.

.yarnrc.yml
This PR explicitly configures yarn pnp settings to the default pnp settings (`nodeLinker: "pnp"` and `pnpMode: "strict"`) as yarn was installing in loose mode on my pc.
=> chore: Explicitly configure yarn pnp.

packages/docs/concepts/custom-blocks.yaml, packages/docs/templates/blog.yaml.njk, packages/docs/templates/footer.yaml.njk, packages/engine/src/createLink.js, packages/engine/test/createLink.test.js, packages/plugins/blocks/blocks-basic/src/blocks/Anchor/examples.yaml, packages/plugins/blocks/blocks-basic/src/blocks/Anchor/schema.json, packages/server-dev/src/components/App.js, packages/server-dev/src/components/LowdefyContext.js, packages/server-dev/src/components/Page.js, packages/server-dev/src/components/Reload.js, packages/server-dev/src/components/block/CategorySwitch.js, packages/server-dev/src/components/block/Container.js, packages/server-dev/src/components/block/List.js, packages/server-dev/src/components/createComponents.js, packages/server-dev/src/components/createLinkComponent.js, packages/server-dev/src/pages/_app.js, packages/server-dev/src/pages/api/request/[pageId]/[requestId].js, packages/server-dev/src/utils/callRequest.js, packages/server-dev/src/utils/setPageId.js, packages/server-dev/src/utils/setupLink.js, packages/server-dev/src/utils/useMutateCache.js, packages/server-dev/src/utils/usePageConfig.js, packages/server-dev/src/utils/useRootConfig.js, packages/server-dev/src/utils/waitForRestartedServer.js, packages/server/src/components/createLinkComponent.js, packages/server/src/utils/setupLink.js
Implementation of next link on server-dev as well as urlQuery and input fixes.
=> Implementation of next link on server-dev 

packages/server-dev/lib/App.js, packages/server-dev/pages/404.js, packages/server-dev/pages/[pageId].js, packages/server-dev/pages/_app.js, packages/server-dev/pages/index.js
=> feat(server-dev): Client working 🏄‍♂️

.pnp.cjs, package.json, packages/build/src/build/buildTypes.js, packages/client/src/Client.js, packages/client/src/Context.js, packages/client/src/DisplayMessage.js, packages/client/src/MountEvents.js, packages/client/src/ProgressBarController.js, packages/client/src/block/Block.js, packages/client/src/initLowdefyContext.js, packages/engine/src/Blocks.js, packages/engine/src/getContext.js, packages/plugins/blocks/blocks-loaders/src/blocks/ProgressBar/ProgressBar.js, packages/server-dev/lib/App.js, packages/server-dev/lib/Page.js, packages/server-dev/lib/Reload.js, packages/server-dev/lib/RestartingPage.js, packages/server-dev/lib/utils/waitForRestartedServer.js, packages/server-dev/manager/watchers/nextBuildWatcher.mjs, packages/server/package.json, yarn.lock
- Add a reset context flag to client so server-dev watcher can tell client to recreate the context.
- Bug fixes to ensure that onInit fires before onMount starts, and render progress bar until final onMount has completed.
- Also add display message implementation.
- Reload needs to pass a flag to client when server is restarting so the client does not crash when new types are added to the server. This flag can also be used to render a "server restarting" screen, for now we delay render as a hack.
=> Client reload fixes and display message

packages/cli/src/utils/copyPluginsFolder.js, packages/utils/node-utils/src/copyDirectory.js
Do not copy node_modules in plugin folders.
=> fix(cli): Do not copy node_modules in plugin folders.

packages/cli/src/commands/dev/runDevServer.js, packages/cli/src/commands/start/runStart.js, packages/cli/src/utils/installServer.js, packages/cli/src/utils/runLowdefyBuild.js, packages/cli/src/utils/runNextBuild.js, packages/cli/src/utils/startUp.js, packages/cli/src/utils/startUp.test.js, packages/operators/package.json, packages/server-dev/manager/getContext.mjs, packages/server-dev/manager/processes/installPlugins.mjs, packages/server-dev/manager/utils/getNextBin.mjs
This pull request fixes bugs related to spawning processes on the Windows platform. These changes have also been verified to work on MacOs.
=> Windows compatibility fixes

packages/operators/src/webParser.js, packages/operators/src/webParser.test.js, packages/plugins/operators/operators-js/src/operators/client/location.js, packages/plugins/operators/operators-js/src/operators/client/location.test.js, packages/plugins/operators/operators-js/src/operators/client/menu.test.js, packages/plugins/operators/operators-js/src/operators/client/request.test.js, packages/plugins/operators/operators-js/src/operators/shared/and.test.js, packages/plugins/operators/operators-js/src/operators/shared/function.js, packages/plugins/operators/operators-js/src/operators/shared/function.test.js, packages/plugins/operators/operators-js/src/operators/shared/or.test.js
Pass window from `webParser` to operator methods and remove `context` from operator methods.
=> Fix location

packages/build/src/build/addDefaultPages/addDefaultPages.js, packages/build/src/build/addDefaultPages/addDefaultPages.test.js, packages/build/src/build/buildConnections.js, packages/build/src/build/buildConnections.test.js, packages/build/src/build/buildMenu.js, packages/build/src/build/buildMenu.test.js, packages/build/src/build/buildPages/buildBlock/buildBlock.js, packages/build/src/build/buildPages/buildBlock/buildEvents.test.js, packages/build/src/build/buildPages/buildBlock/buildSubBlocks.js, packages/build/src/build/buildPages/buildBlock/countBlockOperators.test.js, packages/build/src/build/buildPages/buildPage.js, packages/build/src/build/buildPages/buildPages.js, packages/build/src/build/buildPages/buildPages.test.js, packages/build/src/build/buildPages/buildRequests.test.js, packages/build/src/build/buildPages/buildTestPage.js, packages/build/src/build/buildPages/buildTestPage.test.js, packages/build/src/build/testSchema.js, packages/build/src/build/testSchema.test.js, packages/build/src/build/validateApp.js, packages/build/src/build/validateApp.test.js, packages/build/src/build/validateConfig.js, packages/build/src/build/validateConfig.test.js, packages/build/src/createContext.js, packages/build/src/defaultTypesMap.json, packages/build/src/index.js, packages/build/src/test/testContext.js, packages/cli/src/index.js
This pull request adds a function `buildTestPage` that can be used by `@lowdefy/engine` to keep tests more up to date with changes in build.
Some build functions that were unnecessarily async were also converted to syncronous functions.
=> Add build test page

.pnp.cjs, packages/plugins/actions/actions-core/package.json, packages/plugins/actions/actions-core/src/actions/CallMethod.test.js, packages/plugins/actions/actions-core/src/actions/DisplayMessage.js, packages/plugins/actions/actions-core/src/actions/DisplayMessage.test.js, packages/plugins/actions/actions-core/src/actions/Link.test.js, packages/plugins/actions/actions-core/src/actions/Login.test.js, packages/plugins/actions/actions-core/src/actions/Logout.test.js, packages/plugins/actions/actions-core/src/actions/Request.test.js, packages/plugins/actions/actions-core/src/actions/Reset.test.js, packages/plugins/actions/actions-core/src/actions/ResetValidation.test.js, packages/plugins/actions/actions-core/src/actions/ScrollTo.test.js, packages/plugins/actions/actions-core/src/actions/SetGlobal.test.js, packages/plugins/actions/actions-core/src/actions/SetState.test.js, packages/plugins/actions/actions-core/src/actions/Throw.test.js, packages/plugins/actions/actions-core/src/actions/Validate.test.js, packages/plugins/actions/actions-core/src/actions/Wait.js, packages/plugins/actions/actions-core/src/actions/Wait.test.js, packages/utils/helpers/src/wait.test.js, yarn.lock
=> fix(actions-core): Fix actions core tests.

packages/cli/src/utils/startUp.js
Cli can get configDirectory from LOWDEFY_DIRECTORY_CONFIG during startup.
=> fix(cli): Check env for configDirectory.

packages/api/src/routes/auth/callbacks/addUserFieldsToSession.js, packages/api/src/routes/auth/callbacks/addUserFieldsToToken.js, packages/api/src/routes/auth/callbacks/createCallbacks.js, packages/api/src/routes/auth/callbacks/createJWTCallback.js, packages/api/src/routes/auth/callbacks/createRedirectCallback.js, packages/api/src/routes/auth/callbacks/createSessionCallback.js, packages/api/src/routes/auth/callbacks/createSignInCallback.js, packages/api/src/routes/auth/createProviders.js, packages/api/src/routes/auth/events/createCreateUserEvent.js, packages/api/src/routes/auth/events/createEvents.js, packages/api/src/routes/auth/events/createLinkAccountEvent.js, packages/api/src/routes/auth/events/createSignInEvent.js, packages/api/src/routes/auth/events/createSignOutEvent.js, packages/api/src/routes/auth/events/createUpdateUserEvent.js, packages/api/src/routes/auth/getNextAuthConfig.js, packages/build/src/lowdefySchema.js, packages/server-dev/pages/api/auth/[...nextauth].js, packages/server/pages/api/auth/[...nextauth].js
=> feat: Add userFields feature to map auth provider data to user object.

packages/client/src/auth/createAuthMethods.js
Add callbackUrl and redirect as logout action params
=> feat: Add callbackUrl and redirect as logout action params.

packages/client/src/auth/createAuthMethods.js, packages/client/src/createLinkComponent.js, packages/client/src/initLowdefyContext.js, packages/client/src/setupLink.js, packages/engine/src/Actions.js, packages/operators/src/nodeParser.js, packages/operators/src/nodeParser.test.js, packages/operators/src/webParser.js, packages/operators/src/webParser.test.js, packages/plugins/actions/actions-core/src/actions.js, packages/plugins/actions/actions-core/src/actions/Fetch.js, packages/plugins/actions/actions-core/src/actions/Fetch.test.js, packages/plugins/actions/actions-core/src/actions/ScrollTo.js, packages/plugins/actions/actions-core/src/actions/ScrollTo.test.js, packages/plugins/operators/operators-js/src/operators/client/location.js, packages/plugins/operators/operators-js/src/operators/client/location.test.js, packages/plugins/operators/operators-js/src/operators/client/media.js, packages/plugins/operators/operators-js/src/operators/client/media.test.js, packages/plugins/operators/operators-nunjucks/src/operators/shared/nunjucks.js, packages/server-dev/lib/utils/waitForRestartedServer.js, packages/server-dev/manager/run.mjs
=> Add logout callback url and Fetch action.

packages/client/src/block/CategorySwitch.js, packages/client/src/block/LoadingBlock.js, packages/client/src/block/LoadingContainer.js, packages/client/src/block/LoadingList.js
If no properties of styles are defined on the skeleton definition, it will default the properties and style values of the parent blocks.
=> fix(client): Skeleton to get parent blocks properties and styles.

packages/client/src/block/CategorySwitch.js, packages/client/src/block/Container.js, packages/client/src/block/List.js, packages/client/src/block/LoadingContainer.js, packages/client/src/block/LoadingList.js, packages/layout/src/Area.js, packages/layout/src/BlockLayout.js, packages/layout/src/layoutParamsToArea.js, packages/layout/src/tests/blocks/AutoBlockSim.js, packages/server-dev/next.config.js
layout package should handle default on undefined area or layout params.
=> Apply area and layout default in layout package.

.pnp.cjs, packages/plugins/blocks/blocks-antd/src/blocks/Menu/Menu.js
Fixes menu to set selected keys for the current pageId.
=> Fix menu for selected keys

packages/build/src/build/buildRefs/buildRefs.test.js, packages/build/src/build/buildRefs/getConfigFile.js
Fixes error messages for when a _ref file does not exist.
=> fix: Await content on buildRef to fix ref error message.

packages/plugins/blocks/blocks-aggrid/src/AgGrid.js, packages/plugins/blocks/blocks-aggrid/src/AgGridInput.js, packages/plugins/blocks/blocks-aggrid/src/processColDefs.js
AgGrid `children.cellRenderer` also need to render html.
=> fix(blocks-aggrid): Rec fix cellRenderer.

.pnp.cjs, packages/plugins/operators/operators-moment/README.md, packages/plugins/operators/operators-moment/jest.config.js, packages/plugins/operators/operators-moment/package.json, packages/plugins/operators/operators-moment/src/operators/shared/moment.js, packages/plugins/operators/operators-moment/src/operators/shared/moment.test.js, packages/plugins/operators/operators-moment/src/operatorsClient.js, packages/plugins/operators/operators-moment/src/operatorsServer.js, packages/plugins/operators/operators-moment/src/types.js, yarn.lock
This PR adds the _moment operator..
The _moment operator replaces functionality that was previously part of the _format operator.
=> Add moment operators.

packages/docs/concepts/blocks.yaml
=> grammar fixes

packages/docs/introduction.yaml
=> small typo fix

packages/docs/concepts/connections-and-requests.yaml
Updates the Connections and Request concept page to be relevant for v4.
=> Update Connections and Requests concept page for v4.

packages/docs/concepts/blocks.yaml
Updates Blocks concept page to be relevant for v4.
=> Update Blocks concept page for v4.

packages/docs/concepts/events-and-actions.yaml
General improvements made to the Events and Actions concept page.
=> Update Events and Actions concept page for v4.

packages/api/src/routes/auth/callbacks/addUserFieldsToSession.js, packages/api/src/routes/auth/callbacks/createSessionCallback.js, packages/plugins/blocks/blocks-antd/src/blocks/Label/labelLogic.js
This PR fixes the userFields config if used with an auth adapter.
The minheight on input labels has also been changed.
=> Fix auth callbacks

packages/docs/connections/MongoDB.yaml
Update request type from  MongoDBUpdateMany to MongoDBDeleteOne under MongoDBDeleteOne heading.
Update request type from  MongoDBUpdateMany to MongoDBDeleteOne under MongoDBDeleteOne heading.
=> fix(docs): Fix MongoDB page.

packages/docs/concepts/blocks.yaml
Makes changes to the Blocks concept page. These changes are made to generally improve the page, and make it more relevant to v4.
=> Update Blocks concept page.

packages/server-dev/pages/api/auth/[...nextauth].js, packages/server/pages/api/auth/[...nextauth].js
This PR fixes an error in created in #1331
=> fix: Fix dev server auth api route.

packages/cli/src/index.js, packages/cli/src/program.js
=> feat(cli): Throw if Lowdefy CLI is run with node < v14.

packages/plugins/blocks/blocks-antd/src/blocks/AutoComplete/AutoComplete.js, packages/plugins/blocks/blocks-antd/src/blocks/AutoComplete/schema.json
Fixes AutoComplete block to full width, and only allow for string value and option types.
=> feat(blocks-antd): Fix autocomplete bugs.

packages/plugins/blocks/blocks-aggrid/src/blocks.js
All AgGrid input types was not imported.
=> fix(blocks-aggrid): Import all input types.

packages/docs/howto/v4Migration/v4-migration.md
This PR updates the V4 migration guide with explanations of the changes and examples.
=> feat: Update the V4 migration guide.

packages/api/src/routes/auth/getNextAuthConfig.js
This maps `auth.authPages` to `nextAuthConfig.pages`.
See https://next-auth.js.org/configuration/options#pages settings for next-auth config.
=> feat(api): Map auth.authPages to nextAuthConfig.pages.

packages/build/src/build/buildAuth/buildAuth.test.js, packages/build/src/build/buildAuth/validateAuthConfig.js, packages/build/src/build/buildAuth/validateAuthConfig.test.js, packages/build/src/lowdefySchema.js
Add authPages to lowdefy schema.
=> fix(buiid): Add authPages to ldf schema.

packages/docs/concepts/connections-and-requests.yaml
This PR aims to improve the v4 docs, by adding a working example to the Connections and Requests concept page.
=> feat(docs): Add working example to Connections and Requests concept page.

packages/plugins/blocks/blocks-antd/src/blocks/RadioSelector/RadioSelector.js
~Closes #ISSUE_NUMBER~
The PR fixes the radio selector block not working for non-label/value fields. The fix is similar to the one used in #1330
=> Fix Radio Selector not working for non-label/value fields.

packages/plugins/blocks/blocks-antd/src/blocks/NumberInput/NumberInput.js, packages/plugins/blocks/blocks-antd/src/blocks/NumberInput/schema.json
=> feat(blocks-antd): Add parser property to NumberInput.

packages/plugins/plugins/plugin-next-auth/src/auth/OpenIDConnectProvider.js, packages/plugins/plugins/plugin-next-auth/src/auth/providers.js
This PR adds support for a generic OpenID connect auth provider to the next-auth plugin.
=> Generic OpenID connect auth provider.

pnpm-lock.yaml
Fixes to unupdated pnpm lockfile
=> chore: Fix pnpm lockfile

packages/docs/menus.yaml, packages/docs/operators/_moment.yaml, packages/docs/pages.yaml
This PR adds the moment operator doc.
=> Add moment operator doc

packages/docs/menus.yaml, packages/docs/operators/_intl.yaml, packages/docs/pages.yaml
This PR adds the intl operator doc.
=> Add intl operator doc

packages/docs/pages.yaml
=> fix: Fix broken ref in docs

packages/server/next.config.js
This PR adds the outputStatndalone config option to
=> feat: Add output standalone config to next config for docker deployments

packages/plugins/operators/operators-js/src/operators/shared/intl.js
This PR removes outdated comments from the intl operator.
=> Intl operator chore

packages/docs/operators/_date.yaml, packages/plugins/operators/operators-js/package.json, packages/plugins/operators/operators-js/src/operators/shared/date.js, packages/plugins/operators/operators-js/src/operators/shared/date.test.js
This PR updates the date operator with more methods and tests.
This PR also updates the date operator doc with more methods.
=> Update date operator

packages/docs/concepts/blocks.yaml
Only minor changes to block docs were required.
=> fix(docs): Update block docs.

packages/docs/menus.yaml, packages/docs/migration/v3-to-v4.yaml, packages/docs/pages.yaml
This PR adds a page to the docs containing the migration guide for moving over from version 3 to version 4.
=> Add v3 to v4 migration guide page to the docs.

packages/docs/concepts/custom-styling.yaml, packages/docs/menus.yaml, packages/docs/pages.yaml
This PR adds the Custom Styling Concept page to the docs.
=> Add Custom Styling Concept page.

packages/cli/src/commands/init-vercel/initVercel.js, packages/cli/src/program.js, packages/docs/concepts/cli.yaml, packages/docs/deployment/vercel.yaml, packages/docs/menus.yaml, packages/docs/pages.yaml
=> feat: Add init-vercel CLI command and Vercel deployment docs.

packages/cli/package.json, packages/cli/src/commands/init-docker/.dockerignore, packages/cli/src/commands/init-docker/Dockerfile, packages/cli/src/commands/init-docker/initDocker.js, packages/cli/src/commands/init-vercel/README.md, packages/cli/src/commands/init-vercel/initVercel.js, packages/cli/src/commands/init-vercel/vercel.install.sh, packages/cli/src/commands/init/init.js, packages/cli/src/program.js, packages/docs/concepts/cli.yaml, packages/docs/deployment/docker.yaml, packages/server/next.config.js
=> feat: Add init-docker CLI command and docker docs

packages/build/src/build/buildRefs/buildRefs.test.js, packages/build/src/build/buildRefs/getKey.js, packages/build/src/build/buildRefs/parseRefContent.js, packages/build/src/build/buildRefs/recursiveBuild.js
=> Evaluate build operators before getting key from refDef.

packages/docs/connections/MongoDB.yaml, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBDeleteMany/MongoDBDeleteMany.js, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBDeleteOne/MongoDBDeleteOne.js, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBInsertMany/MongoDBInsertMany.js, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBInsertOne/MongoDBInsertOne.js, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBUpdateMany/MongoDBUpdateMany.js, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBUpdateOne/MongoDBUpdateOne.js, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBUpdateOne/MongoDBUpdateOne.test.js
This PR fixes the MongoDB connection responses for UpdateOne and DeleteOne, fixes the after attribute for UpdateOne and updates the user attribute to meta for all relevant requests. This PR also updates the MongoDB connection docs with the updated responses and log collection information.
=> Fix connection mongodb

packages/docs/connections/AxiosHttp.yaml, packages/plugins/connections/connection-axios-http/src/connections/AxiosHttp/AxiosHttp.test.js, packages/plugins/connections/connection-axios-http/src/connections/AxiosHttp/schema.js
=> fix: Allow AxiosHttp data property to be an array

packages/docs/operators/_object.yaml
Closes #1339
Fixes to _object docs - add methods and fix examples
=> fix(docs): Fix _object operator docs.

packages/docs/blocks/input/PhoneNumberInput.yaml, packages/plugins/blocks/blocks-antd/src/blocks/PhoneNumberInput/PhoneNumberInput.js, packages/plugins/blocks/blocks-antd/src/blocks/PhoneNumberInput/examples.yaml, packages/plugins/blocks/blocks-antd/src/blocks/PhoneNumberInput/schema.json
Use ISO 3166 for allowed regions and default region
=> fix(blocks-antd): Update PhoneNumberInput

packages/docs/deployment/docker.yaml
Fix docker docs for monorepos.
=> fix(docs): Fix monorepo docker deploy docs.

packages/docs/deployment/docker.yaml
Update Dockerfile for monorepos and add env var docs
=> fix(docs): Update docker docs

packages/plugins/blocks/blocks-antd/src/blocks/PhoneNumberInput/PhoneNumberInput.js
This PR fixes the search on the PhoneNumberInput block.
=> Fix search on PhoneNumberInput block.

packages/utils/helpers/src/serializer.js, packages/utils/helpers/src/serializer.test.js
=> fix(serializer): Make _k_ enumerable first.

packages/client/src/createCallRequest.js, packages/client/src/createLinkComponent.js, packages/client/src/initLowdefyContext.js, packages/server-dev/pages/_document.js, packages/server/pages/_document.js
Closes #1554 
Fixes were configured basePath was not passed to requests, web manifest and icons.
=> Fix basepath

packages/docs/blocks/container/Layout.yaml, packages/docs/migration/v3-to-v4.yaml
This PR adds a Layout, Header-Content-Footer example to the docs and migration guide.
=> feat(docs): Add Layout, Header-Content-Footer example

packages/client/src/auth/createAuthMethods.js
Currently the login and logout auth methods promises are not returned, so the Login and Logout actions don't await the promise before completing and moving to the next action.
=> fix: Auth methods should return signin promises.

packages/docs/blocks/container/Carousel.yaml, packages/docs/menus.yaml, packages/docs/pages.yaml, packages/docs/templates/blocks/template.yaml.njk, packages/plugins/blocks/blocks-antd/src/blocks.js, packages/plugins/blocks/blocks-antd/src/blocks/Carousel/Carousel.js, packages/plugins/blocks/blocks-antd/src/blocks/Carousel/Carousel.mock.test.js, packages/plugins/blocks/blocks-antd/src/blocks/Carousel/Carousel.test.js, packages/plugins/blocks/blocks-antd/src/blocks/Carousel/examples.yaml, packages/plugins/blocks/blocks-antd/src/blocks/Carousel/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/Carousel/style.less
This PR adds the Carousel block to the default Lowdefy blocks. It also adds this new block to the docs.
=> Add Carousel block to default Lowdefy blocks.

README.md
Update project readme for v4 launch.
=> v4 readme update.

packages/plugins/blocks/blocks-aggrid/package.json, packages/plugins/blocks/blocks-aggrid/src/AgGrid.js, packages/plugins/blocks/blocks-aggrid/src/AgGridInput.js, packages/plugins/blocks/blocks-aggrid/src/blocks/AgGridAlpine/style.less, packages/plugins/blocks/blocks-aggrid/src/blocks/AgGridAlpineDark/style.less, packages/plugins/blocks/blocks-aggrid/src/blocks/AgGridBalham/style.less, packages/plugins/blocks/blocks-aggrid/src/blocks/AgGridBalhamDark/style.less, packages/plugins/blocks/blocks-aggrid/src/blocks/AgGridInputAlpine/style.less, packages/plugins/blocks/blocks-aggrid/src/blocks/AgGridInputAlpineDark/style.less, packages/plugins/blocks/blocks-aggrid/src/blocks/AgGridInputBalham/style.less, packages/plugins/blocks/blocks-aggrid/src/blocks/AgGridInputBalhamDark/style.less, packages/plugins/blocks/blocks-aggrid/src/blocks/AgGridInputMaterial/style.less, packages/plugins/blocks/blocks-aggrid/src/blocks/AgGridMaterial/style.less, pnpm-lock.yaml
=> feat(blocks-aggrid): Update AgGrid to v29.3.5.

packages/docs/blocks/input/Pagination.yaml, packages/docs/templates/blocks/template.yaml.njk
This PR fixes the bug which was causing blocks on the docs to not render as they would have `visible` set to false.
=> fix(docs): Fix blocks on docs not rendering.

packages/api/src/context/createApiContext.js, packages/api/src/routes/request/evaluateOperators.js, packages/api/src/test/testContext.js, packages/server-dev/lib/server/apiWrapper.js, packages/server-dev/lib/server/log/logError.js, packages/server/lib/server/apiWrapper.js, packages/server/lib/server/log/createLogger.js, packages/server/lib/server/log/logError.js, packages/server/lib/server/log/logRequest.js, packages/server/lib/server/serverSidePropsWrapper.js, packages/server/pages/404.js, packages/server/pages/[pageId].js
This PR updates the logging for errors to included more metadata.
=> Log errors

packages/website/lowdefy.yaml
The home page ID was not configured for the website.
=> Fix website home

packages/plugins/connections/connection-mongodb/package.json, packages/plugins/plugins/plugin-next-auth/package.json, pnpm-lock.yaml
=> fix: Fix next-auth peer dependencies.

packages/build/package.json, packages/build/src/scripts/generateDefaultTypes.js, packages/docs/blocks/display/DocSearch.yaml, packages/docs/head.html, packages/docs/menus.yaml, packages/docs/pages.yaml, packages/docs/public/styles.less, packages/docs/templates/blocks/template.yaml.njk, packages/docs/templates/footer.yaml.njk, packages/docs/templates/header.yaml, packages/plugins/blocks/blocks-algolia/README.md, packages/plugins/blocks/blocks-algolia/jest.config.js, packages/plugins/blocks/blocks-algolia/package.json, packages/plugins/blocks/blocks-algolia/src/blocks.js, packages/plugins/blocks/blocks-algolia/src/blocks/DocSearch/DocSearch.js, packages/plugins/blocks/blocks-algolia/src/blocks/DocSearch/examples.yaml, packages/plugins/blocks/blocks-algolia/src/blocks/DocSearch/schema.json, packages/plugins/blocks/blocks-algolia/src/types.js, packages/server-dev/manager/utils/createCustomPluginTypesMap.mjs, packages/website/lowdefy.yaml, pnpm-lock.yaml
This PR adds the `DocSearch` block, and implements the block in the Lowdefy docs.
=> feat(blocks-algolia): Add DocSearch block.

packages/server-dev/manager/processes/startServer.mjs, packages/server-dev/manager/utils/createStdOutLineHandler.mjs
~Closes #ISSUE_NUMBER~
This PR updates the stdOutLineHandler in server-dev manager to better log pino logs
=> fix(server-dev): Update stdOutLineHandler for pino logs

packages/docs/introduction.yaml, packages/docs/users/reference/next-auth-providers.yaml
=> fix: Documentation fixes.

package.json, packages/server-dev/package.json, packages/server/package.json, pnpm-lock.yaml
Update the pnpm version to 8.7.5. This does change the pnpm lockfile format.
=> chore: Update pnpm version.

packages/plugins/blocks/blocks-antd/src/blocks/Paragraph/Paragraph.js, packages/plugins/blocks/blocks-antd/src/blocks/Paragraph/schema.json, packages/plugins/blocks/blocks-basic/src/blocks/Html/Html.js, packages/plugins/blocks/blocks-basic/src/blocks/Html/schema.json, packages/utils/block-utils/src/HtmlComponent.js, packages/utils/block-utils/src/renderHtml.js
~Closes #ISSUE_NUMBER~
A new event, `onTextSelection` is added to the `HtmlComponent` block util, which is used for the `Html` block. This event makes text selection available using `window.getSelection()`.
=> feat(blocks): Add onTextSelection event to Html.

packages/build/src/build/writeApp.js, packages/build/src/build/writeApp.test.js, packages/build/src/build/writeAuth.js, packages/build/src/build/writeAuth.test.js, packages/build/src/build/writeConfig.js, packages/build/src/build/writeConfig.test.js, packages/build/src/build/writeConnections.js, packages/build/src/build/writeConnections.test.js, packages/build/src/build/writeGlobal.js, packages/build/src/build/writeGlobal.test.js, packages/build/src/build/writeMaps.js, packages/build/src/build/writeMaps.test.js, packages/build/src/build/writeMenus.js, packages/build/src/build/writeMenus.test.js, packages/build/src/build/writePages.js, packages/build/src/build/writePages.test.js, packages/build/src/build/writeRequests.js, packages/build/src/build/writeRequests.test.js, packages/build/src/build/writeTypes.js, packages/build/src/build/writeTypes.test.js
This PR reduces the space in the build output. This results in smaller file sizes.
=> fix(build): Reduce spaces in build output.

packages/docs/blocks/input/MultipleSelector.yaml, packages/docs/blocks/input/Selector.yaml, packages/docs/connections/AWSS3.yaml, packages/docs/connections/AxiosHttp.yaml, packages/docs/connections/Elasticsearch.yaml, packages/docs/connections/GoogleSheet.yaml, packages/docs/connections/KnexRequests.md, packages/docs/connections/MongoDB.yaml, packages/docs/migration/v3-to-v4.yaml, packages/docs/requests/insert_feedback.yaml, packages/docs/requests/insert_newsletter.yaml
This PR updates the examples of requests in the docs to make use of payload.
=> fix(docs): Update example requests to make use of payload.

packages/build/src/build/addKeys.js, packages/build/src/build/addKeys.test.js, packages/build/src/utils/makeId.js
Recursively handle array keys for keyMap.
=> Recursively handle array keys for keyMap

packages/plugins/connections/connection-mongodb/package.json, pnpm-lock.yaml
=> fix(deps): Update dependency mongodb to v4.17.1

packages/utils/helpers/package.json, packages/utils/helpers/src/urlQuery.js, packages/utils/helpers/src/urlQuery.test.js, pnpm-lock.yaml
Removes dependency on query-string package.
This PR handles strings in query params and removes the query-string dependency from urlQuery.
=> fix(helpers): Do not add quotes around strings in query params.

packages/plugins/blocks/blocks-antd/src/blocks/AutoComplete/AutoComplete.js, packages/plugins/blocks/blocks-antd/src/blocks/AutoComplete/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/MultipleSelector/MultipleSelector.js, packages/plugins/blocks/blocks-antd/src/blocks/MultipleSelector/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/NumberInput/NumberInput.js, packages/plugins/blocks/blocks-antd/src/blocks/NumberInput/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/PasswordInput/PasswordInput.js, packages/plugins/blocks/blocks-antd/src/blocks/PasswordInput/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/PhoneNumberInput/PhoneNumberInput.js, packages/plugins/blocks/blocks-antd/src/blocks/PhoneNumberInput/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/Selector/Selector.js, packages/plugins/blocks/blocks-antd/src/blocks/Selector/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/TextArea/TextArea.js, packages/plugins/blocks/blocks-antd/src/blocks/TextArea/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/TextInput/TextInput.js, packages/plugins/blocks/blocks-antd/src/blocks/TextInput/schema.json
Adds onFocus and onBlur evetns to input blocks.
=> Add onFocus and onBlur events to inputs

packages/api/src/routes/request/callRequest.test.js, packages/api/src/routes/request/callRequestResolver.js, packages/docs/plugins/plugins-connections.yaml
ConnectionId is now also passed to request methods.
=> Add connectionId to request object.

packages/docs/blocks/container/Card.yaml, packages/plugins/blocks/blocks-antd/src/blocks/Card/Card.js
This PR adds the cover content area to Card block.
=> feat: Add cover content area to Card block.

packages/build/src/build/buildImports/buildIconImports.js
=> feat: Support Phosphor icon set.

.changeset/strange-pianos-yell.md, packages/client/src/setupLink.js, packages/servers/server-dev/package.json
=> fix: Popups blocked links throw error

packages/client/src/BrandTag.js, packages/website/pages/pricing/sections/pay_for_what_you_use.yaml, packages/website/pages/pricing/sections/pricing_calculator/pricing_calculator.yaml, packages/website/pages/pricing/sections/pricing_calculator/set_prices.yaml, packages/website/pages/pricing/sections/tiers.yaml, packages/website/public/styles.less
This PR updates the pricing styling and pricing calculator.
=> feat: Update pricing styling and pricing calculator.

packages/website/app_config.yaml, packages/website/pages/pricing/sections/compare_features.yaml.njk, packages/website/pages/pricing/sections/compare_features_info.yaml, packages/website/pages/pricing/sections/pay_for_what_you_use.yaml, packages/website/pages/pricing/sections/pricing_calculator/pricing_calculator.yaml, packages/website/pages/pricing/sections/pricing_calculator/set_prices.yaml, packages/website/pages/pricing/sections/tiers.yaml
=> Store rates in app_config for global access.

packages/docs/deployment/node-server.yaml
This PR updates the Deploy with Node.js page in the docs to be relevant to v4.
=> feat(docs): Update Deploy with Node page.

.changeset/silver-cooks-scream.md, packages/cli/src/commands/dev/runDevServer.js, packages/cli/src/commands/start/runStart.js, packages/cli/src/utils/runNextBuild.js
=> fix: Disable next telemetry when disabling Lowdefy telemetry

packages/client/src/BrandTag.js, packages/website/app_config.yaml, packages/website/lowdefy.yaml, packages/website/pages.yaml, packages/website/pages/contact-us/contact-us.yaml, packages/website/pages/contact-us/sections/contact_us.yaml, packages/website/pages/contact-us/sections/contact_us_form.yaml, packages/website/pages/pricing/pricing.yaml, packages/website/pages/pricing/sections/compare_features.yaml.njk, packages/website/pages/pricing/sections/compare_features_info.yaml, packages/website/pages/pricing/sections/cta_buttons/business.yaml, packages/website/pages/pricing/sections/cta_buttons/free.yaml, packages/website/pages/pricing/sections/faq.yaml, packages/website/pages/pricing/sections/pay_for_what_you_use.yaml, packages/website/pages/pricing/sections/pricing_calculator/archive.yaml, packages/website/pages/pricing/sections/pricing_calculator/pricing_calculator.yaml, packages/website/pages/pricing/sections/pricing_calculator/set_prices.yaml, packages/website/pages/pricing/sections/pricing_calculator/sliders.yaml, packages/website/pages/pricing/sections/pricing_calculator/total.yaml, packages/website/pages/pricing/sections/tiers.yaml, packages/website/pages/pricing/sections/trusted_by.yaml, packages/website/public/styles.less, packages/website/requests/insert_query.yaml, packages/website/shared/customers_marquee.yaml, packages/website/shared/header/menu.yaml
This PR adds the contact us section to the website.
=> feat: Add contact-us to website.

.changeset/calm-dodos-boil.md, .changeset/heavy-islands-explode.md, packages/plugins/connections/connection-mongodb/package.json, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/getCollection.js, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/getCollection.test.js, pnpm-lock.yaml
This PR updates the mongodb dependency for the mongodb connection to version 6.3.0.
=> feat(connection-mongodb): Update dependency mongodb to v6.3.0.

.changeset/ten-actors-mate.md, packages/docs/connections/GoogleSheet.yaml, packages/docs/templates/footer.yaml.njk
=> fix: fix broken link and use improved reference to Google Docs

packages/client/src/BrandTag.js
=> fix: Fix show branding logic.

packages/plugins/blocks/blocks-aggrid/package.json, pnpm-lock.yaml
=> chore: Fix plugin-aggrid lowdefy utils deps version.

packages/website/pages/pricing/sections/cta_buttons/business.yaml, packages/website/pages/pricing/sections/cta_buttons/free.yaml
=> fix(website): Fix links to lowdefy cloud app.

packages/website/pages/contact-us/sections/contact_us_form.yaml, packages/website/pages/pricing/pricing.yaml
=> fix: Adjust and add widths.

.changeset/eleven-parents-flash.md, .changeset/forty-ears-do.md, .changeset/heavy-baboons-hope.md, packages/plugins/blocks/blocks-antd/src/blocks/Modal/Modal.js, packages/plugins/blocks/blocks-antd/src/blocks/Modal/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/MultipleSelector/MultipleSelector.js, packages/plugins/blocks/blocks-antd/src/blocks/MultipleSelector/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/Selector/Selector.js, packages/plugins/blocks/blocks-antd/src/blocks/Selector/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/TextInput/TextInput.js, packages/plugins/blocks/blocks-antd/src/blocks/TextInput/schema.json
=> Block property updates.

.changeset/clever-ears-decide.md, .changeset/healthy-cars-bathe.md, packages/plugins/blocks/blocks-antd/src/blocks/Breadcrumb/Breadcrumb.js, packages/plugins/blocks/blocks-basic/src/blocks/Box/Box.js, packages/plugins/blocks/blocks-basic/src/blocks/Box/schema.json
onPaste on Box and breadcrumb bug fix.
=> onPaste on Box and bug fix.

.changeset/shaggy-swans-swim.md, packages/plugins/blocks/blocks-antd/src/blocks/Pagination/Pagination.js
Pagination was not handled by a controlled internal state, causing it to break when used with visible conditions.
=> Bug fix on Pagination

.changeset/cuddly-radios-switch.md, packages/docs/actions/SetFocus.yaml, packages/docs/menus.yaml, packages/docs/pages.yaml, packages/plugins/actions/actions-core/src/actions.js, packages/plugins/actions/actions-core/src/actions/SetFocus.js, packages/plugins/actions/actions-core/src/actions/SetFocus.test.js
=> SetFocus Action

.changeset/spicy-ears-happen.md, packages/plugins/blocks/blocks-antd/src/blocks/Pagination/Pagination.js
=> Pagination skip

.changeset/gentle-socks-love.md, packages/docs/blocks/container/Popover.yaml, packages/docs/blocks/input/TreeSelector.yaml, packages/docs/menus.yaml, packages/docs/pages.yaml, packages/plugins/blocks/blocks-antd/src/blocks.js, packages/plugins/blocks/blocks-antd/src/blocks/Popover/Popover.js, packages/plugins/blocks/blocks-antd/src/blocks/Popover/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/Popover/style.less, packages/plugins/blocks/blocks-antd/src/blocks/TreeSelector/TreeSelector.js, packages/plugins/blocks/blocks-antd/src/blocks/TreeSelector/schema.json, packages/plugins/blocks/blocks-antd/src/blocks/TreeSelector/style.less
This PR adds the Popover and TreeSelector blocks.
=> New blocks

.changeset/cuddly-radios-switch.md, .changeset/giant-geese-reflect.md, .changeset/plenty-flowers-type.md, packages/docs/blocks/display/S3Download.yaml, packages/docs/blocks/input/S3UploadButton.yaml, packages/docs/blocks/input/S3UploadDragger.yaml, packages/docs/blocks/input/S3UploadPhoto.yaml, packages/docs/connections/AWSS3.yaml, packages/docs/menus.yaml, packages/docs/pages.yaml, packages/plugins/plugins/plugin-aws/src/blocks/S3Download/S3Download.js, packages/plugins/plugins/plugin-aws/src/blocks/S3Download/schema.json, packages/plugins/plugins/plugin-aws/src/blocks/S3Download/style.less, packages/plugins/plugins/plugin-aws/src/blocks/S3UploadButton/S3UploadButton.js, packages/plugins/plugins/plugin-aws/src/blocks/S3UploadButton/schema.json, packages/plugins/plugins/plugin-aws/src/blocks/S3UploadDragger/S3UploadDragger.js, packages/plugins/plugins/plugin-aws/src/blocks/S3UploadDragger/schema.json, packages/plugins/plugins/plugin-aws/src/blocks/S3UploadDragger/style.less, packages/plugins/plugins/plugin-aws/src/blocks/S3UploadPhoto/S3UploadPhoto.js, packages/plugins/plugins/plugin-aws/src/blocks/S3UploadPhoto/schema.json, packages/plugins/plugins/plugin-aws/src/blocks/utils/getOnPaste.js, packages/plugins/plugins/plugin-aws/src/blocks/utils/getS3Upload.js, packages/plugins/plugins/plugin-aws/src/blocks/utils/useFileList.js, packages/plugins/plugins/plugin-aws/src/connections/AwsS3Bucket/AwsS3PresignedPostPolicy/AwsS3PresignedPostPolicy.js
- `AwsS3PresignedPostPolicy` to include `fields` property. Useful for setting `Content-Type` etc.
- Refactor `S3UploadPhoto` and `S3UploadButton`.
- Add `singleFile` and `maxCount` to `S3UploadPhoto` and `S3UploadButton` blocks.
- Add `S3UploadDragger` and `S3Download` blocks.
=> S3 Block Changes.

.github/workflows/release.yaml, .github/workflows/test-branches.yml, .github/workflows/test-pulls.yml
=> chore: Update github actions workflow dependencies

.changeset/lazy-bikes-suffer.md, packages/docs/connections/MongoDB.yaml, packages/plugins/connections/connection-mongodb/package.json, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBBulkWrite/MongoDBBulkWrite.js, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBBulkWrite/MongoDBulkWrite.test.js, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBBulkWrite/schema.js
This PR adds the `MongoDBBulkWrite` request to the Mongodb connection. This request executes [bulkWrite operations](https://www.mongodb.com/docs/manual/reference/method/db.collection.bulkWrite/#write-operations) in the collection specified in the connectionId.
=> Add MongoDBBulkWrite request type to the MongoDB connection.

.changeset/great-elephants-flash.md, packages/docs/operators/_nunjucks.yaml, packages/utils/nunjucks/src/index.js, packages/utils/nunjucks/src/uniqueFilter.js, packages/utils/nunjucks/src/uniqueFilter.test.js
=> 'unique' nunjucks filter

.changeset/tiny-apples-share.md, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBCollection.js, packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBCollection.test.js
This PR adds missing MongoDbBulkWrite request reference to the MongoDBCollection.
=> Add MongoDbBulkWrite to MongoDBCollection requests.

.changeset/violet-papayas-breathe.md, packages/plugins/blocks/blocks-antd/src/blocks/PhoneNumberInput/PhoneNumberInput.js
- Add null checks and default values in AddOnSelect onChange handler
- Implement safe property access in PhoneNumberInput onChange event
=> PhoneNumberInput - undefined (reading 'dial_code')

packages/docs/blocks/display/MarkdownWithCode.yaml
=> fix: Typo in MarkdownWithCode docs.

.changeset/late-cameras-roll.md, packages/plugins/blocks/blocks-antd/src/blocks/DateRangeSelector/DateRangeSelector.js, packages/plugins/blocks/blocks-antd/src/blocks/DateSelector/DateSelector.js, packages/plugins/blocks/blocks-antd/src/blocks/DateTimeSelector/DateTimeSelector.js, packages/plugins/blocks/blocks-antd/src/blocks/MonthSelector/MonthSelector.js, packages/plugins/blocks/blocks-antd/src/blocks/MultipleSelector/MultipleSelector.js, packages/plugins/blocks/blocks-antd/src/blocks/Popover/Popover.js, packages/plugins/blocks/blocks-antd/src/blocks/Selector/Selector.js, packages/plugins/blocks/blocks-antd/src/blocks/WeekSelector/WeekSelector.js
Randomize popup dom element ids to fix popups where multiple elements of same ids are mounted on a page.
=> Randomize popup dom element ids.

packages/plugins/blocks/blocks-antd/src/blocks/MultipleSelector/MultipleSelector.js
=> feat(blocks-antd): Fix elementId on MultipleSelector.

packages/build/src/build/buildApi/buildControl.test.js, packages/build/src/build/buildApi/buildRoutine.test.js, packages/build/src/build/buildApi/buildRoutine/validateStep.js, packages/build/src/build/buildApi/buildStep.test.js
Make step connection ids required.
=> Make connectionId required.

packages/api/src/context/createEvaluateOperators.js, packages/api/src/routes/endpoints/handleRequest.js, packages/operators/src/serverParser.js, packages/plugins/operators/operators-js/src/operators/server/step.js, packages/plugins/operators/operators-js/src/operatorsServer.js
=> feat: Add _step operator for use in api.

packages/build/src/build/buildJs/buildJs.js, packages/build/src/build/buildJs/writeJs.js, packages/plugins/operators/operators-js/src/operators/server/item.test.js, packages/plugins/operators/operators-js/src/operators/server/js.js, packages/plugins/operators/operators-js/src/operators/server/step.test.js
- Implemented _js operator.
- Added step, item, and state to server js operators.
- Added test case for item and step.
=> Js operator

.changeset/quiet-lobsters-end.md, packages/docs/operators/_nunjucks.yaml, packages/utils/nunjucks/src/index.js, packages/utils/nunjucks/src/urlQueryFilter.js, packages/utils/nunjucks/src/urlQueryFilter.test.js
This PR renames the nunjucks link filter to urlQuery.
=> Rename nunjucks link filter to urlQuery.

packages/api/src/routes/endpoints/control/controlLog.js, packages/api/src/routes/endpoints/control/controlReject.js, packages/build/src/build/buildApi/buildControl.test.js, packages/build/src/build/buildApi/buildEndpoint.js, packages/build/src/build/buildApi/buildRoutine/controlTypes.js, packages/build/src/build/buildApi/buildRoutine/validateStep.js, packages/build/src/build/buildApi/buildStep.test.js, packages/engine/src/callAPIHandler.js
Fixes to Lowdefy APIs from beta testing.
=> Api updates

.changeset/six-houses-draw.md, packages/servers/server-dev/manager/processes/installPlugins.mjs
=> fix: Set shell to true when on windows in installPlugins.

.changeset/purple-squids-turn.md, packages/plugins/blocks/blocks-echarts/package.json, pnpm-lock.yaml
=> chore: Update echarts to 5.5.1.

packages/plugins/blocks/blocks-aggrid/src/AgGrid.js, packages/plugins/blocks/blocks-aggrid/src/AgGridInput.js, packages/plugins/blocks/blocks-aggrid/src/assignRowId.js
PR #1818 broke editing aggrid cells and drag and drop functionality. Only applies when no row id is provided. 
This also removes the index property on change events. The rowIndex is the aggrid field that provides the index value
=> Fix aggrid input edit and row drag and drop.

.changeset/quiet-phones-tan.md, packages/plugins/blocks/blocks-antd/src/blocks/ControlledList/ControlledList.js, packages/plugins/blocks/blocks-antd/src/blocks/ControlledList/schema.json
This PR adds the minItems property to the ControlledList block. This property controls the minimum number of items that the list should contain.
=> Add minItems property to ControlledList block.

packages/docs/templates/blocks/template.yaml.njk, packages/docs/templates/general.yaml.njk, packages/docs/templates/generic_block.yaml.njk
Removes version 3 alert banner.
=> Remove version 3 alert
