- .eslintrc.yaml
- packages/blockTools/src/index.js
- packages/blockTools/src/loadWebpackFederatedModule.js
- packages/blockTools/src/useDynamicScript.js
- packages/cli/src/commands/dev/shell/bootstrap.js
- packages/renderer/src/page/block/LoadBlock.js
- Add webpack module federation scripts `useDynamicScript` and `loadWebpackFederatedModule`.
- Reduce the number of dynamics scripts loaded. Closes #218 
- Use webpack module federation scripts from block-tools
- Use webpack module federation scripts from block-tools
> feat(blockTools): move module fed functions to blockTools

- packages/blockTools/package.json
- packages/blockTools/src/runMockRenderTests.js
- react-test-renderer should be a dependency, closes #248
> fix(blockTools): react-test-renderer should be a dependency

- packages/blockTools/src/mediaToCssObject.js
- packages/blockTools/src/mediaToCssObject.test.js
- mediaToCssObject with `null` should not throw.
> Fix @lowdefy/block-tools

- packages/engine/src/Blocks.js
- packages/engine/test/Block/Blocks.test.js
- blocks visible should evaluate only when not equal to false, PR #277.
> fix(engine): visible should evaluate only when not equal to false

- packages/blocks/blocksECharts/README.md
- packages/docs/blocks/display/EChart.yaml
Hi, my name is Sven and I'm a member of Apache ECharts PMC. Very glad to see `lowdefy` has chosen Apache ECharts. I came across and notice some issue in doc. It should be `Apache ECharts` rather than `ECharts` because right now it is TLP of Apache Foundation.   Could you merge this PR, so there would be no brand issue. Thanks, and excellent job you guys have done here,
> chore: add `Apache`

- packages/operators/src/web/request.js
- packages/operators/test/testContext.js
- packages/operators/test/web/request.test.js
- packages/operators/test/web/request_details.test.js
Closes: No issue
All getters return `null` as their default value. When using the `_request` operator with dot notation, the default value returned was `undefined`, instead of `null`. This PR makes `_request` work like other getters.
> fix(operators): _request getter default value should be null.

- packages/docs/connections/MongoDB.yaml
- packages/graphql/package.json
- packages/graphql/src/connections/MongoDBCollection/getCollection.js
- yarn.lock
Closes #696
Updated the mongodb driver to 4.1.0 and the options for MongoDBAggregation documentation.
The following options are no longer used within the respective commands:
- DeleteMany, DeleteOne
- j: boolean
- w: number | string
- wtimeout: number
- InsertMany, InsertOne, UpdateMany, UpdateOne
- forceServerObjectId: boolean
- j: boolean
- w: integer | string
- wtimeout: integer
> feat(graphql): Mongodb driver and MongoDBAggregation docs update.

- packages/blocks/blocksAntd/src/blocks/Divider/Divider.js
- packages/blocks/blocksAntd/tests/__snapshots__/Divider.mock.test.js.snap
- packages/blocks/blocksAntd/tests/__snapshots__/Divider.test.js.snap
Closes #790
Divider title should only render if defined.
> fix(blocksAntd): Divider not to render empty title, closes #790

- packages/docs/connections/AxiosHttp.yaml
- packages/graphql/src/connections/AxiosHttp/AxiosHttp/AxiosHttp.js
- packages/graphql/src/connections/AxiosHttp/AxiosHttp/AxiosHttp.test.js
Closes #794 
This PR adds `httpAgentOptions` and `httpsAgentOptions` to the AxiosHttp request, that can be used to specify the options passed to the Node.js `http.Agent` and `https.Agent` classes.
It also adds documentation for functions that can now be passed to AxiosHttp using the `_function` operator.
https://www.loom.com/share/f46ef1ca2534416080266245e0bc3610
> Axios http agent options

- packages/blocks/blocksAntd/src/blocks/Tooltip/Tooltip.js
- packages/blocks/blocksAntd/tests/__snapshots__/Tooltip.mock.test.js.snap
Closes #812
This PR fixes the issue where a Tooltip block rendered an empty tooltip when `properties.title` was not defined
> fix(blocksAntd): Fix undefined Tooltip title showing empty tooltip.

- packages/blocks/blocksAntd/src/blocks/MultipleSelector/MultipleSelector.json
- packages/blocks/blocksAntd/src/blocks/ParagraphInput/ParagraphInput.js
Closes None
This PR fixes a typo in the `ParagraphInput` block which would have prevented the `copyable.text` property from working
> fix(blocksAntd): Fix typo in Paragraph input copyable text property.

- packages/blocks/blocksAntd/src/blocks/Paragraph/Paragraph.js
- packages/blocks/blocksAntd/src/blocks/Title/Title.js
- packages/docs/blocks/display/Title.yaml
Paragraph and Title blocks no longer return `[object object]` when copying text.
> fix(blocksAntd): Copyable fix added to Paragraph and Title blocks.

- packages/docs/connections/AxiosHttp.yaml
Fixes a typo in the `AxiosHttp` connection docs where the type name was misspelled as `AxiosHTTP`.
> fix(docs): Fix AxiosHttp connection type spelling in docs.

- packages/cli/src/commands/dev/getExpress.js
- packages/cli/src/commands/dev/shell/bootstrap.js
- packages/docs/concepts/cli.yaml
Closes #840
See #668
If the `--blocks-server-url` CLI option is set, the `dev` command will now use the renderer component served from the configured url.
> fix(cli): Use renderer served from blocks server url if configured.

- packages/blocks/blocksAntd/src/blocks/AutoComplete/AutoComplete.js
- packages/blocks/blocksAntd/src/blocks/ButtonSelector/ButtonSelector.js
- packages/blocks/blocksAntd/src/blocks/CheckboxSelector/CheckboxSelector.js
- packages/blocks/blocksAntd/src/blocks/MultipleSelector/MultipleSelector.js
- packages/blocks/blocksAntd/src/blocks/RadioSelector/RadioSelector.js
- packages/blocks/blocksAntd/src/blocks/Selector/Selector.js
- packages/blocks/blocksAntd/tests/__snapshots__/AutoComplete.mock.test.js.snap
- packages/blocks/blocksAntd/tests/__snapshots__/ButtonSelector.test.js.snap
- packages/blocks/blocksAntd/tests/__snapshots__/CheckboxSelector.test.js.snap
- packages/blocks/blocksAntd/tests/__snapshots__/MultipleSelector.mock.test.js.snap
- packages/blocks/blocksAntd/tests/__snapshots__/RadioSelector.test.js.snap
- packages/blocks/blocksAntd/tests/__snapshots__/Selector.mock.test.js.snap
Previous changes to the way HTML was rendered in selector options caused the option filter function to error if no HTML component was found. Now, an HtmlComponent is always rendered as the option label for consistency.
> fix(blocksAntd): Fix selector option labels and filter function.

- packages/plugins/blocks/blocks-antd/src/blocks/MultipleSelector/MultipleSelector.js
- packages/plugins/blocks/blocks-antd/src/blocks/Selector/Selector.js
Closes #968
The user will now see the loading state between multiple searches that are debounced.
> fix(blocks-antd): Added debounce condition to Selector and MultipleSelector.

- .yarnrc.yml
- packages/docs/connections/AxiosHttp.yaml
- packages/graphql/src/connections/AxiosHttp/AxiosHttp.test.js
- packages/graphql/src/connections/AxiosHttp/AxiosHttpSchema.json
Closes #1158
This PR updates the JSON Schema to allow for arrays passed to the data property, as the schema was to restrictive and was causing errors.
> fix(graphql): Update AxiosHttp schema to allow for data arrays

- packages/docs/templates/blocks/propertiesFormTransformer.js
- packages/docs/templates/test/button.test.js
- packages/plugins/blocks/blocks-antd/src/blocks/ConfirmModal/ConfirmModal.js
Closes #1160 
Icons now work for `ConfirmModal`. Fix on docs.
> fix(blocks-antd): Fix confirm modal button icons, closes #1160

- packages/client/src/initLowdefyContext.js
- packages/client/src/setupLink.js
The `createLink` function needs access to the `lowdefy` object to be able to set inputs. This was removed in a previous change to the `setupLink` function. This PR restores the previous `setupLink` function.
> fix(client): Fix setupLink - createLink needs lowdefy for input.

- packages/server-dev/lib/Page.js
The `usePageConfig` was being used after a conditional return statement, resulting in a `Rendered more hooks than during the previous render.` react error.
> fix(server-dev): Fix react hooks used incorrectly.

- packages/client/src/MountEvents.js
The onMount async event was not triggered if the block was unmounted before the event started. This caused an issue because the progress bar done event was not dispatched. The `onMountAsync` and `onInitAsync` event will now always be triggered, even if the block is unmounted before the event is started.
> fix(client): On mount async method should always be called.

- packages/api/src/routes/request/callRequest.js
- packages/engine/src/Requests.js
- packages/engine/src/actions/createGetRequestDetails.test.js
- packages/engine/src/actions/createRequest.js
- packages/engine/src/actions/createRequest.test.js
- packages/engine/test/Requests.test.js
- packages/engine/test/getContext.test.js
- packages/plugins/operators/operators-js/src/operators/client/request.js
- packages/plugins/operators/operators-js/src/operators/client/request.test.js
- packages/server-dev/pages/api/request/[pageId]/[requestId].js
- packages/server/pages/api/request/[pageId]/[requestId].js
When a request is called, set the `response` to `null` before firing request and call update. This makes loading states on requests easy to implement. Also add payload and blockId to `[context.requests[requestId]`.
> feat(engine): Set request to null and update before calling request.

- .pnp.cjs
- packages/plugins/blocks/blocks-aggrid/package.json
- packages/plugins/blocks/blocks-aggrid/src/AgGrid.js
- packages/plugins/blocks/blocks-aggrid/src/AgGridInput.js
- packages/server-dev/package.json
- yarn.lock
AgGrid removed support for rendering html strings in v27. This PR uses lowdefy `renderHtml` to render dompurified html in AgGrid cells.
See https://github.com/ag-grid/ag-grid/issues/5226
> fix: Allow cellRenderer in Aggrid to render html.

- packages/client/src/initLowdefyContext.js
- packages/engine/src/actions/createGetUrlQuery.js
- packages/engine/src/actions/createGetUrlQuery.test.js
- packages/engine/src/createLink.js
- packages/operators/src/webParser.js
- packages/operators/src/webParser.test.js
- packages/plugins/operators/operators-js/src/operators/client/url_query.js
- packages/plugins/operators/operators-js/src/operators/client/url_query.test.js
- packages/server-dev/manager/utils/BatchChanges.mjs
urlQuery to be read directly form `window.location.search` instead of from lowdefy object, so we remove the duplication.
> Fix url query

- packages/docs/blocks/list/ControlledList.yaml
- packages/docs/connections/AxiosHttp.yaml
Closes #1289 
The filePath variable for the ControlledList block in the docs has been corrected, thereby remediating the 404 bug described in #1289
> fix(docs): correct filePath for ControlledList

- packages/build/src/build/buildPages/buildBlock/buildEvents.js
- packages/build/src/build/buildPages/buildBlock/buildEvents.test.js
When try is defined on an event, and catch is not, catch will be set to be an empty array.
This stops an error from being thrown when try is used without catch, and adds default behaviour for this case.
> Add default for catch when try is defined for an event and catch is not.

- packages/server-dev/lib/auth/getServerSession.js
- packages/server-dev/pages/api/auth/[...nextauth].js
- packages/server-dev/pages/api/page/[pageId].js
- packages/server-dev/pages/api/request/[pageId]/[requestId].js
- packages/server-dev/pages/api/root.js
- packages/server/lib/auth/getServerSession.js
- packages/server/pages/api/auth/[...nextauth].js
- packages/server/pages/api/request/[pageId]/[requestId].js
https://next-auth.js.org/configuration/nextjs
https://github.com/nextauthjs/next-auth/issues/1535
This PR changes the getServerSession function to use the unstable_getServerSession function, which does not make an additional fetch request to the auth api to get the session. This can have large performance and reliability benefits.
> fix: Fix next-auth getServerSession.

- packages/cli/src/utils/installServer.js
This fixes the `installServer` process in CLI to output the npm or yarn install output at the log level. This output was previously at the info level. This was broken in #1304 so that no output was logged.
> fix: Log server install output at debug level.

- packages/docs/connections/AxiosHttp.yaml
Closes #1352
The 'headers' key should be nested under the key 'properties', in the current docs it appears at the same indentation level and that throws a Schema error.
- [-] Tests added
- [-] Documentation added/updated
- [-] Code has been formatted with Prettier
> docs: Update AxiosHttp.yaml

- packages/cli/src/utils/installServer.js
- packages/server-dev/.npmrc
- packages/server-dev/manager/processes/installPlugins.mjs
- packages/server-dev/package.json
- packages/server/.npmrc
- packages/server/package.json
This PR adds a `.npmrc` file to both server packages with `strict-peer-dependencies=false` so that builds do not break when plugins with missing peer dependencies are installed. pnpm will still warn on missing dependencies, which is the same behaviour as yarn.
The  `--no-frozen-lockfile` option is also passed to pnpm when installing the server from CLI to add plugins, since without this builds fail in CI environments. We are installing new packages, so we expect the lockfile to change.
> fix: Fix server pnpm installs.

- packages/build/src/build/buildRefs/getUserJavascriptFunction.js
This PR updates the import of user defined ref resolver and transformer functions to use file URLs instead of absolute paths, since the later can fail with a `ERR_UNSUPPORTED_ESM_URL_SCHEME ` error.
> Fix _ref resolver and transformer functions on windows.

- packages/api/src/context/createApiContext.js
- packages/server-dev/pages/api/auth/[...nextauth].js
- packages/server-dev/pages/api/page/[pageId].js
- packages/server-dev/pages/api/request/[pageId]/[requestId].js
- packages/server-dev/pages/api/root.js
- packages/server/pages/404.js
- packages/server/pages/[pageId].js
- packages/server/pages/api/auth/[...nextauth].js
- packages/server/pages/api/request/[pageId]/[requestId].js
- packages/server/pages/index.js
This PR fixes an error "too many files open" which is caused by opening the `config.json` file multiple times when creating the API context.
It changes the file read to an import in the Next server.
This means `createApiContext` is now syncronous, which was needed in the auth api to use a configured logger.
> fix(api): Fix "too many files open" error in api.

- packages/api/src/context/createApiContext.js
- packages/api/src/context/createReadConfigFile.js
- packages/api/src/context/createReadConfigFile.test.js
- packages/build/src/utils/readConfigFile.js
- packages/server-dev/lib/fileCache.js
- packages/server-dev/pages/api/auth/[...nextauth].js
- packages/server-dev/pages/api/page/[pageId].js
- packages/server-dev/pages/api/request/[pageId]/[requestId].js
- packages/server-dev/pages/api/root.js
- packages/server/lib/fileCache.js
- packages/server/pages/404.js
- packages/server/pages/[pageId].js
- packages/server/pages/api/auth/[...nextauth].js
- packages/server/pages/api/request/[pageId]/[requestId].js
- packages/server/pages/index.js
- packages/utils/helpers/src/LRUCache.js
- packages/utils/helpers/src/cachedPromises.js
- packages/utils/helpers/src/cachedPromises.test.js
- packages/utils/helpers/src/index.js
This PR fixs the file read cache in the API which was not working. Files are now cached over all server requests. A least recently updated file cache is also added.
> fix: Cache API file reads across all requests.

- packages/build/src/scripts/generateDefaultTypes.js
The moment operator was never added to the generateDefaultTypes script, this PR just adds it.
> feat(build): Add operators-moment to generateDefaultTypes

- packages/plugins/blocks/blocks-qr/src/blocks/QRScanner/QRScanner.js
QRScanner block should only call stop when active and start when not active.
> fix(blocks-qr): Don't call start and stop if scanner is not running.

- packages/plugins/blocks/blocks-antd/src/blocks/Paragraph/style.less
- packages/plugins/blocks/blocks-antd/src/blocks/Title/style.less
In prod, when the copy action is used on `Paragraph` and `Title`, tooltip styles are required.
> fix(blocks-antd): Import tooltip styles on Paragraph and Title for copy.

- package.json
- packages/server-dev/manager/watchers/lowdefyBuildWatcher.mjs
This PR fixes a bug where the watchPaths CLI config was not working. The paths were based of of the wrong base path.
> Fix watch path CLI config for relative paths.

- packages/build/src/build/validateConfig.js
- packages/build/src/build/validateConfig.test.js
- packages/build/src/build/writePluginImports/writeStyleImports.js
- packages/build/src/lowdefySchema.js
- packages/server-dev/manager/run.mjs
- packages/server-dev/manager/watchers/nextBuildWatcher.mjs
- packages/server-dev/next.config.js
- packages/server/next.config.js
This PR adds support for user defined style ([LESS](https://lesscss.org)) files. If a `styles.less` file is present in the `public` folder, that file will be imported as part of the build.
Other `.less` and `.css` files in the `public` folder can be imported, and `.less` and `.css` can be imported from the dependencies of plugins.
Less variables can be set in the `styles.less` file. In particular, Ant Design V4 theme variables can be set.
As an example:
```less
@import  'antd/lib/style/dark.less';
@import './other.css';
@primary-color: #2ac8bb;
```
Support for the `config.theme.lessVariables` config option has been dropped as it can easily be achieved using a `styles.less` file.
> User styles

- packages/plugins/blocks/blocks-color-selectors/src/blocks/ColorSelector/ColorPicker.js
- packages/plugins/blocks/blocks-color-selectors/src/blocks/ColorSelector/ColorSelector.js
- packages/plugins/blocks/blocks-color-selectors/src/blocks/ColorSelector/examples.yaml
- packages/plugins/blocks/blocks-color-selectors/src/blocks/ColorSelector/schema.json
Closes ~#ISSUE_NUMBER~ 
This PR fixes the bug in which the color selector would not correctly display the selected color when the value was updated through the use of SetState.
This PR also removes the undefinedColor property from the ColorSelector block.
> Fix Color Selector SetState bug.

- packages/docs/actions/Throw.yaml
For v4 we considered renaming `Throw` to `Break` and then not throwing an error but just breaking the action chain. After some consideration, we've decided to support both. Thus, keep `Throw` as implemented in v3 and add `Break` as an additional feature in the future.
> Docs: Keep Throw action the same as v3.

- packages/plugins/operators/operators-js/src/operators/shared/string.js
- packages/plugins/operators/operators-js/src/operators/shared/string.test.js
This PR adds null to the list of valid types for the string operator methods which make use of a single argument and prep.
> fix(operators-js): Add null as valid type to string operator methods.

- packages/engine/src/Blocks.js
- packages/engine/test/Block/validate.test.js
Closes #1465 
This PR fixes the validation bug which appeared when required was set dynamically. This bug caused validation to occur when required evaluated to false, which is not the desired behaviour.
> Fix validation when using a dynamic approach to setting required.

- packages/cli/package.json
- packages/cli/src/utils/checkForUpdatedVersions.js
- pnpm-lock.yaml
This PR adds an error that is thrown when a user tries to run a version 3 app using the version 4 CLI. It adds a dependency on semver, which is used to validate the version and to get the major version.
> Throw error when user runs v3 app using v4 CLI

- packages/operators/src/getFromObject.test.js
- packages/operators/src/webParser.js
The `_user: true` operator expression should return null, not and empty object.
> fix: _user: true should return null if logged out.

- packages/plugins/blocks/blocks-google-maps/README.md
- packages/plugins/blocks/blocks-google-maps/src/blocks/GoogleMaps/GoogleMaps.json
- packages/plugins/blocks/blocks-google-maps/src/blocks/Map.js
This PR adds the ability to add marker clusterers to the google map block. Marker Clusterers can be added under the markerClusterers property of the GoogleMaps block. 
This PR also includes a fix for zoom not working when an initial center and zoom are not supplied in the block config.
> Add Marker Clusterers to Google Map block.

- packages/cli/src/utils/getLowdefyYaml.js
- packages/cli/src/utils/getLowdefyYaml.test.js
- packages/cli/src/utils/startUp.js
- packages/cli/src/utils/startUp.test.js
- packages/cli/src/utils/validateVersion.js
This PR renames `checkForUpdatedVersions` to `validateVersion`. It also adds a check to skip the version validation if the `init` command has been used. This check is similar to the one used in `getLowdefyYaml`.
> Fix v3 undefined version error when calling lowdefy init.

- packages/plugins/blocks/blocks-antd/src/blocks/PhoneNumberInput/PhoneNumberInput.js
- packages/plugins/blocks/blocks-antd/src/blocks/PhoneNumberInput/schema.json
- packages/plugins/blocks/blocks-antd/src/blocks/PhoneNumberInput/style.less
- packages/plugins/blocks/blocks-antd/src/blocks/TextInput/TextInput.js
- packages/plugins/blocks/blocks-antd/src/blocks/TextInput/schema.json
This PR adds an additional property, `replaceInput`, to the PhoneNumberInput and TextInput blocks. This property allows a regular expression to be defined which will be used to sanitise input as the user is typing.
> Add replaceInput property to PhoneNumberInput and TextInput blocks.

- packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBDeleteMany/MongoDBDeleteMany.test.js
- packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBDeleteOne/MongoDBDeleteOne.test.js
- packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBInsertMany/MongoDBInsertMany.test.js
- packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBInsertOne/MongoDBInsertOne.test.js
- packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBUpdateMany/MongoDBUpdateMany.test.js
- packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBUpdateOne/MongoDBUpdateOne.js
- packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBUpdateOne/MongoDBUpdateOne.test.js
- packages/plugins/connections/connection-mongodb/test/findLogCollectionRecordTestMongoDb.js
This PR adds handling for upsert true with a log collection on MongoDBUpdateOne. This PR also adds a helper test function findLogCollectionRecordTestMongoDb and log collection tests for MongoDBUpdateOne, MongoDBInsertOne, MongoDBDeleteOne, MongoDBUpdateMany, MongoDBInsertMany and MongoDBDeleteMany.
> Log collection mongodb

- packages/api/src/routes/request/callRequest.test.js
- packages/build/src/build/addKeys.js
- packages/build/src/build/addKeys.test.js
- packages/build/src/build/buildRefs/recursiveBuild.js
- packages/docs/migration/v3-to-v4.yaml
- packages/operators/src/buildParser.js
- packages/operators/src/serverParser.js
- packages/operators/src/serverParser.test.js
- packages/operators/src/webParser.js
- packages/operators/src/webParser.test.js
- packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/MongoDBAggregation/MongoDBAggregation.test.js
- packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/serialize.js
- packages/plugins/connections/connection-mongodb/src/connections/MongoDBCollection/serialize.test.js
- packages/plugins/operators/operators-js/src/operators/shared/json.test.js
- packages/plugins/operators/operators-yaml/src/operators/shared/yaml.test.js
- packages/server-dev/manager/watchers/nextBuildWatcher.mjs
- packages/utils/helpers/src/serializer.js
- packages/utils/helpers/src/serializer.test.js
This PR changes the format of dates and errors used by the serializer helper function. Previously, the serialiser used the `{"_date": "iso_date_string"}` format to represent dates when serialised to JSON, but this caused bugs due to interactions with the `_date` operator. 
The serialiser is used extensively, including in the build process, and it was modifying the user `_date` operator configuration.
The serialiser now uses the `{"~d": "iso_date_string"}` to represent dates, and therefore doesn't interfere with the `_date` operator.
The serialisation of errors was also changed to `~e`, and the `_r_` and `_k_` config keys were renamed to `~r` and `~k`.
> Fix serialization of dates and errors

- packages/api/src/routes/auth/callbacks/addUserFieldsToSession.js
- packages/api/src/routes/auth/callbacks/addUserFieldsToToken.js
Using the `set` helper functions allows to use dot notation in the `auth.userFields` config. Previously, this did not work as expected:
```yaml
auth:
userFields:
profile.name: name
profile.picture: picture
```
> fix(api): Use lowdefy get,set helpers in auth user fields.

- packages/plugins/blocks/blocks-antd/src/blocks/DateTimeSelector/DateTimeSelector.js
This PR adds onChange to the DateTimeSelector. This fixes the allowClear bug that prevented a user from clearing a selected date time.
> fix(blocks-antd): Add onChange to DateTimeSelector.

- packages/docs/tutorial/tutorial-actions-operators.yaml
- packages/docs/tutorial/tutorial-requests-sql.yaml
In the tutorial "4. Interactive pages with actions and operators" :
- replaces the wrong reference to Google Sheets with a reference to SQLite
In the tutorial "6. Saving data to SQL", fixes :
- a mismatch between the name of the secret in the .env file and the name used in the page file.
- a mismatch between the name used for the id of the request : `save_new_ticket` and the name used to reference the request in the next step.
Both problems caused errors.
> fix : Fix variable name mismatches and reference to Google Sheets in tutorial documentation

- packages/plugins/blocks/blocks-antd/src/blocks/Tabs/Tabs.js
Refactor tabs to update to items prop. Older version of Tabs pane is deprecated.
> chore(blocks-antd): Refactor tabs to update to items prop.

- packages/plugins/blocks/blocks-antd/src/blocks/Tabs/style.less
This PR sets ant-tabs-tabpane-hidden class to display none to handle the Tabs block stacking bug.
> fix(blocks-antd): Set ant-tabs-tabpane-hidden class to display none.

- packages/plugins/blocks/blocks-antd/src/blocks/Tabs/style.less
- packages/server-dev/package.json
- packages/server/package.json
- pnpm-lock.yaml
4.2.0 does not process css vars correctly.
4.2.0 does not process css vars correctly.
> Revert less update

- packages/plugins/blocks/blocks-antd/src/blocks/MultipleSelector/MultipleSelector.js
This PR adds a fix to the MultipleSelector block to check if an option exists before checking if there is a tag. This PR also adds a loading message to the placeholder while the options are loading.
> fix(blocks-antd): Check if option exists before checking tag.

- .changeset/mighty-vans-repair.md
- packages/build/src/build/buildTypes.js
> fix:  Remove unnecessary warning message on build "_id is used but not defined"

- .changeset/real-keys-decide.md
- packages/docs/migration/v3-to-v4.yaml
- packages/docs/operators/_change_case.yaml
- packages/plugins/operators/operators-change-case/package.json
- packages/plugins/operators/operators-change-case/src/operators/shared/change_case.js
- packages/plugins/operators/operators-change-case/src/operators/shared/change_case.test.js
- pnpm-lock.yaml
This PR upgrades the change-case dependency to 5.4.0
This is a breaking change and effects the `_change_case` operator.
Changes to the `_change_case` operator:
- Options splitRegex and stripRegexp are no longer supported.
- paramCase has been renamed to kebabCase
- headerCase has been renamed to trainCase
- The following options have been added:
- locale
- mergeAmbiguousCharacters
- prefixCharacters
- split
- suffixCharacters
- Added pascalSnakeCase which transforms a string into a string of capitalized words with underscores between words.
> BREAKING CHANGE Upgrade change-case dependency to 5.4.0.

- .changeset/giant-geese-reflect.md
- packages/plugins/blocks/blocks-antd/src/blocks/Pagination/Pagination.js
Closes #N/A
Unset initial pageSize value for Pagination block, fixes a bug where it would not use the initial value as specified in the pageSizeOptions property.
> Pagination bug fix

- packages/cli/src/commands/dev/runDevServer.js
- packages/cli/src/commands/start/runStart.js
- packages/cli/src/utils/installServer.js
- packages/cli/src/utils/runLowdefyBuild.js
- packages/cli/src/utils/runNextBuild.js
… windows.
The CLI is failing to run on latest versions of Node.js on windows to the security fix for CVE-2024-27980. We need to set the `shell` process option true to spawn a `.cmd` file.
https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2#command-injection-via-args-parameter-of-child_processspawn-without-shell-option-enabled-on-windows-cve-2024-27980---high
> fix(cli): Set shell process option true when spawning pnpm command on windows.

- .changeset/red-mayflies-fold.md
- packages/plugins/blocks/blocks-antd/src/blocks/Drawer/Drawer.js
- packages/plugins/blocks/blocks-antd/src/blocks/Drawer/schema.json
- Previous `triggerSetOpen` function split into dedicated functions. This should improve code maintainability, and fixes and issue where the `onClose` event would be executed twice.
- Added new `afterOpenChange` events. The actions in these events execute after the drawer's closing animation is done.
- Use of `open` instead of `visible` to match the new Ant Design API convention (and makes `afterOpenChange` work).
> Drawer enhancements.

- .changeset/honest-goats-arrive.md
- packages/plugins/plugins/plugin-aws/src/blocks/S3UploadButton/schema.json
- packages/plugins/plugins/plugin-aws/src/blocks/S3UploadDragger/schema.json
- packages/plugins/plugins/plugin-aws/src/blocks/S3UploadPhoto/schema.json
Adds the missing `onProgress`, `onSuccess`, `onRemove` and `onError` events to the `S3UploadButton`, `S3UploadDragger` and `S3UploadPhoto` block schemas.
> Add missing events to S3Upload block schemas
